### ISSUE TITLE
v0.9.0 Integration failed to load

### ISSUE THREAD

**Issue by Viertakt** [rospogrigio/daikin_residential#1]
First of all; let me tell you I love the work you're doing!! Please provide me a way to buy you a coffee(or beer)!

**Describe the bug**  
Integration setup failure, asks for IP adress (without any inputfield), then fails to set up integration.

**To Reproduce**  
-Add the integration via "+add integration"
-Add via configuration.yaml "daikin_residential:"

**Screenshots & Logfiles**  
![error_daikin_residential](https://user-images.githubusercontent.com/77019845/125176828-03a07e00-e1d7-11eb-9a35-d9d3be5a1ec5.png)
<details><summary>Home assistant Log</summary>
Logger: homeassistant.config_entries
Source: util/async_.py:140
First occurred: 22:38:03 (1 occurrences)
Last logged: 22:38:03

Error setting up entry daikin for daikin_residential
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/daikin_residential/__init__.py", line 63, in async_setup_entry
    await daikin_api.getCloudDeviceDetails()
  File "/config/custom_components/daikin_residential/__init__.py", line 208, in getCloudDeviceDetails
    return await self.doBearerRequest("/v1/gateway-devices")
  File "/config/custom_components/daikin_residential/__init__.py", line 141, in doBearerRequest
    res = requests.get(resourceUrl, headers=headers)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.9/http/client.py", line 1264, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 214, in putrequest
    return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
    check_loop()
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
    raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/daikin_residential/__init__.py, line 141: res = requests.get(resourceUrl, headers=headers)
</details>

**Versions:**  
## System Health

version | core-2021.7.1
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.9.5
os_name | Linux
os_version | 4.19.0-17-amd64
arch | x86_64
timezone | UTC

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4994
Installed Version | 1.13.2
Stage | running
Available Repositories | 911
Installed Repositories | 3

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 10 (buster)
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.8
docker_version | 20.10.7
disk_total | 908.6 GB
disk_used | 75.7 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.12.5), RPC Shutdown (2.2), File editor (5.3.1), InfluxDB (4.1.0), Node-RED (9.1.1), ZeroTier One (0.11.1), Mosquitto broker (6.0.1), otmonitor (dev), MariaDB (2.3.0), AdGuard Home (4.1.6), Nginx Proxy Manager (0.11.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 2
views | 5
mode | storage

</details>

HACS v1.13.2
daikin_residential v0.9.0

**Additional context**  
Succesfully obtained my API token, placed in the /config folder of Home Assistant.

**Comment by rospogrigio** [comment]
Yeah I know, it was not yet ready for prime time!! I'm already struggling to solve this, in my test environment it works but in Hassio it fails... give me some time.

**Comment by rospogrigio** [comment]
OK I seem to have fixed the issue, everything is working to me. Feel free to use the integration and report feedbacks thank you!
Enjoy!

**Comment by cchriso** [comment]
just updated to your new version - works like a charm. Thanks for your time and also big thanks to @Apollon77
