### ISSUE TITLE
Isn´t there any device or entity ?

### ISSUE THREAD

**Issue by copadewe** [rospogrigio/daikin_residential#129]
Hi, i got my Daikin perfera today, have the BRP069C4X modul.
Oh it´s a  Daikin Perfera FTXM50R R32 WiFi Inverter Wand-Klimageräte-Set
After installing and enter my mail and pass, it logged in but I not see any item.
Maybe someone can tell me were I´m wrong?

Any help is appreciated.
Oliver

**Comment by copadewe** [comment]
sorry changed the post in this moment when you wrote :-) I already changed the login.

**Comment by copadewe** [comment]
> You need to post any relevant messages you find in home-assistant.log .

2023-04-04 16:28:06.312 ERROR (MainThread) [homeassistant.components.daikin.config_flow] Error creating device, 192.168.178.28 is not supported.

**Comment by rospogrigio** [comment]
Which url? 
I have never seen that error, I can't provide any help, sorry.

**Comment by copadewe** [comment]
@rospogrigio sorry, That must be an entrie from the original Daikin AC integration, i deleted all now.
In the log there is no more "Daikin" others yes where I know why, but please look, maybe you found it?!

![grafik](https://user-images.githubusercontent.com/118108456/229887265-6fbb0f22-7d11-4805-b678-63ededee3261.png)

Log:
2023-04-04 20:13:29.080 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration landroid_cloud which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 20:13:29.080 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 20:13:29.081 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration kaco which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 20:13:29.081 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration daikin_residential which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 20:13:29.082 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration oilfox which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 20:13:29.082 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 20:13:29.083 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration localtuya which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 20:13:29.083 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration rademacher which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 20:13:29.084 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-04-04 20:13:34.015 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform kaco
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 498, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 196, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
  File "/config/custom_components/kaco/sensor.py", line 96, in unique_id
    return self.coordinator.data["extra"]["serialno"] + self._valueKey
TypeError: 'NoneType' object is not subscriptable
2023-04-04 20:13:34.017 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up kaco platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 301, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 442, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 498, in _async_add_entity
    entity.add_to_platform_start(
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 196, in add_to_platform_start
    if self.unique_id is None or self.device_class is None:
  File "/config/custom_components/kaco/sensor.py", line 96, in unique_id
    return self.coordinator.data["extra"]["serialno"] + self._valueKey
TypeError: 'NoneType' object is not subscriptable
2023-04-04 20:13:34.593 INFO (SyncWorker_7) [fritzconnection] Unable to retrieve resource 'http://192.168.178.57:49000/igddesc.xml' from the device.
2023-04-04 20:13:34.600 INFO (SyncWorker_1) [fritzconnection] Unable to retrieve resource 'http://192.168.178.28:49000/igddesc.xml' from the device.
2023-04-04 20:13:34.602 INFO (SyncWorker_0) [fritzconnection] Unable to retrieve resource 'http://192.168.178.58:49000/igddesc.xml' from the device.
2023-04-04 20:13:37.620 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Worx - oscheithauer@gmail.com for landroid_cloud
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 226, in _call
    req.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.worxlandroid.com/api/v2/users/certificate

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/landroid_cloud/__init__.py", line 64, in async_setup_entry
    result = await _async_setup(hass, entry)
  File "/config/custom_components/landroid_cloud/__init__.py", line 208, in _async_setup
    await hass.async_add_executor_job(cloud.connect, False, False)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 269, in connect
    with self._get_cert() as cert:
  File "/usr/local/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/__init__.py", line 324, in _get_cert
    certresp = self._api.get_cert()
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 135, in get_cert
    calldata = self._call("/users/certificate")
  File "/usr/local/lib/python3.10/site-packages/pyworxcloud/api.py", line 236, in _call
    raise NotFoundError()
pyworxcloud.exceptions.NotFoundError
2023-04-04 20:13:37.797 WARNING (SyncWorker_8) [custom_components.localtuya.climate] [bf8...mqu] Entity climate.az_ir_heizung is requesting unknown DPS index 1
2023-04-04 20:13:37.809 WARNING (SyncWorker_8) [custom_components.localtuya.climate] [bf8...mqu] Entity climate.az_ir_heizung is requesting unknown DPS index 4
2023-04-04 20:13:37.809 WARNING (SyncWorker_8) [custom_components.localtuya.climate] [bf8...mqu] Entity climate.az_ir_heizung is requesting unknown DPS index 4
2023-04-04 20:13:38.893 WARNING (MainThread) [homeassistant.components.bluetooth_le_tracker.device_tracker] No Bluetooth LE devices to track!
2023-04-04 20:13:38.894 ERROR (MainThread) [homeassistant.components.device_tracker] Error setting up platform legacy bluetooth_le_tracker
2023-04-04 20:13:44.008 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform kaco is taking over 10 seconds.
2023-04-04 20:14:21.629 WARNING (MainThread) [homeassistant.config_entries] Config entry 'MFC-J6710DW E68605M1F134316' for brother integration not ready yet; Retrying in background
2023-04-04 20:22:35.132 ERROR (MainThread) [homeassistant.components.roku.coordinator] Error fetching roku data: Invalid response from API: Timeout occurred while connecting to device
2023-04-04 20:22:38.446 ERROR (MainThread) [homeassistant.components.wallbox] Error fetching wallbox data: 
2023-04-04 20:28:56.861 ERROR (MainThread) [homeassistant.components.roku.coordinator] Error fetching roku data: Invalid response from API: Error occurred while communicating with device
2023-04-04 20:30:31.891 ERROR (MainThread) [frontend.js.latest.202303091] :0:0 ResizeObserver loop completed with undelivered notifications.
2023-04-04 20:37:43.134 ERROR (MainThread) [homeassistant.components.roku.coordinator] Error fetching roku data: Invalid response from API: Timeout occurred while connecting to device
