### ISSUE TITLE
Breaking change cause sw to fail

### ISSUE THREAD

**Issue by ridderr** [rospogrigio/daikin_residential#140]
Last update on HA (2023.6.0b0) causes integration to fail.
`Deze fout is ontstaan door een aangepaste integratie.

Logger: homeassistant.config_entries
Source: custom_components/daikin_residential/daikin_api.py:54
Integration: Daikin Residential Controller (documentation, issues)
First occurred: 07:41:34 (3 occurrences)
Last logged: 07:46:17

Error setting up entry Daikin for daikin_residential
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/__init__.py", line 84, in async_setup_entry
    daikin_api = DaikinApi(hass, entry)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/daikin_api.py", line 54, in __init__
    self.openIdClient = Client(client_id=self.openIdClientId, config=configuration)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/oic/__init__.py", line 354, in __init__
    self.settings = settings or OicClientSettings()
                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 96, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 51, in __init__
    self.client_cert = client_cert
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 73, in __setattr__
    raise SettingsException(
oic.utils.settings.SettingsException: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).
`

**Comment by jwillemsen** [comment]
2033.6 seems to upgrade python, see https://rc.home-assistant.io/blog/2023/05/31/release-20236/#python-311-and-major-performance-upgrades, maybe that is related

**Comment by jwillemsen** [comment]
See https://github.com/CZ-NIC/pyoidc/issues/839 and https://github.com/CZ-NIC/pyoidc/issues/839

**Comment by jwillemsen** [comment]
Can you try to edit locally `custom_components/daikin_residential/manifest.json` and change `1.4.0` to `1.6.0` for `oic`

**Comment by ridderr** [comment]
Changed that and also installed another update of Home Assistant to 2023.6.0b1. The integration is working again. Not sure if this is because of above change or upgrade of HA.
Many Thanks.

**Comment by jwillemsen** [comment]
Thanks for testing, made a pull request for the required change

**Comment by jwillemsen** [comment]
@rospogrigio or @ridderr Can you close this issue?

**Comment by Marc1979** [comment]
Thanks for the quick fix (and sorry for opening a new issue)!
