### ISSUE TITLE
Unable to set swing mode (BRP069C4x)

### ISSUE THREAD

**Issue by genex89** [rospogrigio/daikin_residential#145]
I have a daikin siesta ATXF25E with BRP069C4x wifi card. I can control the climate control just fine, but not turning the vertical swing on and off. I get the following error:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/daikin_residential/device.py:334
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 20:12:43 (2 occurrences)
Last logged: 20:12:44

[1516607120] Please provide a valid datapoint definition that exists in the data structure
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1910, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1950, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 226, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 811, in entity_service_call
    future.result()  # pop exception if have
    ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1034, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 851, in _handle_entity_call
    await result
  File "/config/custom_components/daikin_residential/climate.py", line 247, in async_set_swing_mode
    await self._device.async_set_swing_mode(swing_mode)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 275, in async_set_swing_mode
    await self.setValue(ATTR_HSWING_MODE, new_hMode)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 135, in setValue
    return await self.set_data(cmd_set[0], cmd_set[1], cmd_set[2], value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/device.py", line 334, in set_data
    raise Exception(
Exception: Please provide a valid datapoint definition that exists in the data structure

**Comment by jwillemsen** [comment]
Please attach the device diagnostics (see Settings/Device&Services/Daikin Residential Controller/Download diagnostics) and a HA log with debugging enabed

**Comment by pplucky** [comment]
> Please attach the device diagnostics (see Settings/Device&Services/Daikin Residential Controller/Download diagnostics) and a HA log with debugging enabed

As @genex89 never reported back, but I'm facing the same issue with controllers BRP069C4x and BRP069B4x (same exact error message), I'll take over and provide the data you requested.

**HA log** (all other messages after activating debug log level are mqtt or esphome related):
```
2023-08-01 22:48:04.701 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Running websocket_api script
2023-08-01 22:48:04.702 INFO (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Executing step call service
2023-08-01 22:48:04.709 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Please provide a valid datapoint definition that exists in the data structure
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 703, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 665, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 848, in entity_service_call
    response_data = task.result()  # pop exception if have
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1192, in async_request_call
    return await coro
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 892, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/daikin_residential/climate.py", line 247, in async_set_swing_mode
    await self._device.async_set_swing_mode(swing_mode)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 275, in async_set_swing_mode
    await self.setValue(ATTR_HSWING_MODE, new_hMode)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 135, in setValue
    return await self.set_data(cmd_set[0], cmd_set[1], cmd_set[2], value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/device.py", line 334, in set_data
    raise Exception(
Exception: Please provide a valid datapoint definition that exists in the data structure
```

**Diagnostics files (personal data redacted)**
[BRP069C4x](https://github.com/rospogrigio/daikin_residential/files/12234365/daikin_residential-diagnostic-BRP069C4x.json.txt)


[BRP069B4x](https://github.com/rospogrigio/daikin_residential/files/12234369/daikin_residential-diagnostic-BRP069B4x.json.txt)

Please let me know if you need anything else.

Thanks in advance.

**Comment by jwillemsen** [comment]
Looks this device doesn't have a `horizontal` swing mode, only `vertical`, looks some code doesn't check that. Maybe the following change works for you, see https://github.com/rospogrigio/daikin_residential/commit/5d1553afac18122030e66bd917340b23c3ad7d94. Can you make the same change locally and let us know?

**Comment by pplucky** [comment]
No error appeared, but it didn't seem to fully work properly.

Would you be able to review [this fix](https://github.com/pplucky/daikin_residential/blob/master/custom_components/daikin_residential/daikin_base.py) I took from another repository (@droscy I believe), as this seems to work properly for me?

**Comment by Xander-V** [comment]
For my perfera, I have the following options for swing mode in onecta:

Horizontal: OFF - ON
Vertical: OFF - ON - Comfort

![image](https://github.com/rospogrigio/daikin_residential/assets/97856913/faa1e9b7-8552-4d88-84a5-52342031dba3)

In your application, one can only choose:

![image](https://github.com/rospogrigio/daikin_residential/assets/97856913/70f750b6-27fa-4f66-94c8-bef282c7b81c)

When setting it to comfort with onecta or the remote control, your application tells me it is in 3D mode, so exactly same as for horizontal on and vertical on, which means I'm missing some options. A non-breaking possible fix could be an interpretation like this:

![image](https://github.com/rospogrigio/daikin_residential/assets/97856913/73b84607-63b8-42d8-86ba-594370ff9ca3)

I would be more then willing to test, let me know if I can.

**Comment by thanosa75** [comment]
Hi - have the same problem - did this get fixed at the end?

**Comment by jwillemsen** [comment]
Maybe you can try https://github.com/jwillemsen/daikin_residential_altherma/tree/jwi-climatecontrolrework, that integration now has also support for the daikin AC units

**Comment by jwillemsen** [comment]
See https://github.com/jwillemsen/daikin_residential_altherma/releases for a forked integration which does have this support
