### ISSUE TITLE
Error setting up entry Daikin for daikin_residential

### ISSUE THREAD

**Issue by mbay0r** [rospogrigio/daikin_residential#150]
Hi!

since i have updated HA the integration does not work anymore. 
Is it possible to fix this error? 

Thanks a lot

```
Home Assistant 2023.6.1
Supervisor 2023.06.1
Operating System 10.2
Frontend 20230608.0 - latest
```

```
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/daikin_residential/daikin_api.py:54
Integration: Daikin Residential Controller (documentation, issues)
First occurred: 9. Juni 2023 um 19:42:36 (5 occurrences)
Last logged: 08:42:12

Error setting up entry Daikin for daikin_residential
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/__init__.py", line 84, in async_setup_entry
    daikin_api = DaikinApi(hass, entry)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/daikin_api.py", line 54, in __init__
    self.openIdClient = Client(client_id=self.openIdClientId, config=configuration)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/oic/__init__.py", line 354, in __init__
    self.settings = settings or OicClientSettings()
                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 96, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 51, in __init__
    self.client_cert = client_cert
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 73, in __setattr__
    raise SettingsException(
oic.utils.settings.SettingsException: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).

```

**Comment by mbay0r** [comment]
sorry, did not see the update of the integration.
