### ISSUE TITLE
[Issue]: Error setting up entry Daikin for daikin_residential_altherma

### ISSUE THREAD

**Issue by AdamWyrzykowski** [rospogrigio/daikin_residential#152]
Integration does not start since yestarday.
Home Assistant 2023.6.1 Supervisor 2023.06.1 Operating System 10.2
Here are logs:

2023-06-12 11:58:18.903 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant

2023-06-12 11:58:18.904 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration daikin_residential_altherma which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-06-12 11:58:32.160 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Daikin for daikin_residential_altherma
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/daikin_residential_altherma/__init__.py", line 84, in async_setup_entry
daikin_api = DaikinApi(hass, entry)
^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/daikin_residential_altherma/daikin_api.py", line 56, in __init__
self.openIdClient = Client(client_id=self.openIdClientId, config=configuration)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/oic/oic/__init__.py", line 354, in __init__
self.settings = settings or OicClientSettings()
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 96, in __init__
super().__init__(
File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 51, in __init__
self.client_cert = client_cert
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 73, in __setattr__
raise SettingsException(
oic.utils.settings.SettingsException: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).

**Comment by jwillemsen** [comment]
See https://github.com/rospogrigio/daikin_residential/issues/151
