### ISSUE TITLE
"Failed to set up" since update to 6.1

### ISSUE THREAD

**Issue by viper539** [rospogrigio/daikin_residential#153]
Hi,

i get this in the debug Log:
`
2023-06-13 12:10:58.808 ERROR (MainThread) [custom_components.daikin_residential.config_flow] Failed to initialize DaikinApi: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).
2023-06-13 12:11:22.473 DEBUG (MainThread) [custom_components.daikin_residential.daikin_api] Initialing Daikin Residential API...
2023-06-13 12:11:22.473 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Daikin for daikin_residential
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/__init__.py", line 84, in async_setup_entry
    daikin_api = DaikinApi(hass, entry)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/daikin_api.py", line 54, in __init__
    self.openIdClient = Client(client_id=self.openIdClientId, config=configuration)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/oic/__init__.py", line 354, in __init__
    self.settings = settings or OicClientSettings()
                                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 96, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 51, in __init__
    self.client_cert = client_cert
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 73, in __setattr__
    raise SettingsException(
oic.utils.settings.SettingsException: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).
`

Onecta-App is working fine.

**Comment by jwillemsen** [comment]
See #140
