### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by fedepupo** [rospogrigio/daikin_residential#155]
I've update Home Assistant at last version 2023.6.2 and Daikin Residential Integration no longer works

```
2023-06-19 16:52:21.887 ERROR (MainThread) [custom_components.daikin_residential.config_flow] Failed to initialize DaikinApi: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).

2023-06-19 16:52:21.941 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Daikin for daikin_residential
Traceback (most recent call last):

File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/daikin_residential/__init__.py", line 84, in async_setup_entry
daikin_api = DaikinApi(hass, entry)
^^^^^^^^^^^^^^^^^^^^^^

File "/config/custom_components/daikin_residential/daikin_api.py", line 54, in __init__
self.openIdClient = Client(client_id=self.openIdClientId, config=configuration)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "/usr/local/lib/python3.11/site-packages/oic/oic/__init__.py", line 354, in __init__
self.settings = settings or OicClientSettings()
^^^^^^^^^^^^^^^^^^^

File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 96, in __init__
super().__init__(
File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 51, in __init__
self.client_cert = client_cert
^^^^^^^^^^^^^^^^

File "/usr/local/lib/python3.11/site-packages/oic/utils/settings.py", line 73, in __setattr__
raise SettingsException(
oic.utils.settings.SettingsException: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).
```

thanks

**Comment by jwillemsen** [comment]
See #140
