### ISSUE TITLE
[Issue]: can't load at startup or no updates of status/comands  

### ISSUE THREAD

**Issue by lperco** [rospogrigio/daikin_residential#157]
Can't load integration or no update of status of Havc and comands do not change HVAC status.

Device firmware updated with last version. ONECTA works fine.

These are logs and file attached:

***
Logger: homeassistant.bootstrap
Source: bootstrap.py:507
First occurred: 07:45:25 (4 occurrences)
Last logged: 07:48:25

Waiting on integrations to complete setup: daikin_residential
****
Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: custom_components.daikin_residential
Source: custom_components/daikin_residential/__init__.py:61
Integration: Daikin Residential Controller (documentation, issues)
First occurred: 07:53:31 (1 occurrences)
Last logged: 07:53:31

Failed to reload integration: 'daikin_residential'
******
[home-assistant_daikin_residential_2023-06-22T08-08-23.996Z.log](https://github.com/rospogrigio/daikin_residential/files/11844547/home-assistant_daikin_residential_2023-06-22T08-08-23.996Z.log)

**Comment by rospogrigio** [comment]
Looks like you are having issues with a template sensor (sensor.rain_last_hour). I don't see errors actually related to the daikin_residential integration, but make sure you have installed the latest release (2.3.1).
Hope this helps.

**Comment by lperco** [comment]
Thanks for reply,
I've removed templete sensor not working for OpenWeatherMap plug issue. 
I've last version 2.3.1
But Daikin residential still can't load after reboot after about and more 5 minutes of "initialising" 
I've re-download Daikin Residential but error still present

A new log loaded hope this help

***
2023-06-23 10:48:35.092 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: daikin_residential
2023-06-23 10:49:35.202 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: daikin_residential
2023-06-23 10:50:35.293 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: daikin_residential
2023-06-23 10:51:35.368 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: daikin_residential
2023-06-23 10:52:35.472 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: daikin_residential
2023-06-23 10:52:44.867 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Daikin for daikin_residential
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/__init__.py", line 85, in async_setup_entry
    devices = await daikin_api.getCloudDevices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/daikin_api.py", line 488, in getCloudDevices
    self.json_data = await self.getCloudDeviceDetails()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/daikin_api.py", line 484, in getCloudDeviceDetails
    return await self.doBearerRequest("/v1/gateway-devices")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/daikin_api.py", line 117, in doBearerRequest
    return await self.doBearerRequest(resourceUrl, options, True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/daikin_api.py", line 99, in doBearerRequest
    res = await self.hass.async_add_executor_job(func)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
*****
Thanks for help


[home-assistant_daikin_residential_2023-06-23T08-53-21.271Z.log](https://github.com/rospogrigio/daikin_residential/files/11846743/home-assistant_daikin_residential_2023-06-23T08-53-21.271Z.log)
