### ISSUE TITLE
[Issue]: integration not starting with latest HA (docker)

### ISSUE THREAD

**Issue by gismo2004** [rospogrigio/daikin_residential#165]
Home Assistant 2023.8.2
Frontend 20230802.0 - latest

`Setup failed for custom integration daikin_residential: Unable to import component: No module named 'oic'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/daikin_residential/__init__.py", line 13, in <module>
    from .daikin_api import DaikinApi
  File "/config/custom_components/daikin_residential/daikin_api.py", line 11, in <module>
    from oic.oic import Client
ModuleNotFoundError: No module named 'oic'`

Manifest is pointing to oic 1.6.0

**Comment by gismo2004** [comment]
seems like, it has been an upstream issue --> 2023.8.4 works
