### ISSUE TITLE
Compatibility Confirmation - BRP069C82

### ISSUE THREAD

**Issue by DJMAXIZA** [rospogrigio/daikin_residential#189]
Good day, I can confirm this integration works with FCAG cartridge unit, using the BRP069C82 module. Hope this helps

**Comment by jwillemsen** [comment]
Great info, maybe you can also try https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.0.0, that integration also support the Daikin AC Units and exports more data to HA

**Comment by DJMAXIZA** [comment]
Thank you for this recommendation, it does add numerous other useful sensors and information for the FCAG unit! I have another unit (FTXM with BRP069C4x controller), which seems to have inconsistent results with the above integration. For most part it pulls information, but the climate entity (for climate card), either does not work properly, or it disappears (no longer available). I am still playing around with it though and hoping to get it working with this integration.

**Comment by jwillemsen** [comment]
You can enable debug logging (see readme.md), that hopefully tells some more what is happening

**Comment by PskNorz** [comment]
@jwillemsen Hey does its work with multy split with BRP069C4x controller too?

**Comment by jmtatsch** [comment]
Yes, I have a multisplit perfera with BRP069C4x controllers which works as expected.

**Comment by jwillemsen** [comment]
Yes, I have at home a multi split with BRP069C4x and a Altherma to test with

**Comment by PskNorz** [comment]
Just to be sure I am talking for this integration if is working with my splits https://github.com/jwillemsen/daikin_residential_altherma/tree/v3.0.0

**Comment by PskNorz** [comment]
Alright I will change thanks!

**Comment by DJMAXIZA** [comment]
Hi, firstly, merry Christmas!

Since the latest upgrade (3.2.8), my split with BRP069C4x is working properly, thank you much. I had the issue that on earlier version, there was no climate entity for this AC, but is now sorted. Many thanks

Regards

Derick

From: ***@***.***
Sent: 25 December 2023 15:13
To: ***@***.***
Reply to: ***@***.***
Cc: ***@***.***; ***@***.***
Subject: Re: [rospogrigio/daikin_residential] Compatibility Confirmation - BRP069C82 (Issue #189)



Yes, that will work, use the latest release

**Comment by PskNorz** [comment]
I deleted daikin_residential integrantion and install the altherma one but it doesnt find my splits  units.

**Comment by jwillemsen** [comment]
@PskNorz Make sure you use https://github.com/jwillemsen/daikin_residential_altherma, I have added a PR to get it listed on HACS, but on HACS it is still not there, so don't use HACS right now for this integration

**Comment by DJMAXIZA** [comment]
@jwillemsen , hi. On my FCAG cartridge unit, using the BRP069C82 module, I don't see any energy usage sensors. For the life of me, I can't remember if it was available in previous version of integration, or if it is just not available for this unit at all?

The other thing I noticed, is that any changes made to unit from HA (like temp, mode), takes between 10 and 30 seconds (sometimes longer) to take effect. Guess it is the API delay? From Onecta app, it responds within about 5 seconds.

Lastly, changing swing on this unit, produces error, with following from log:

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:27:44 (1 occurrences)
Last logged: 14:27:44

[547199449664] cannot access local variable 'res' where it is not associated with a value
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/daikin_residential_altherma/climate.py", line 556, in async_set_swing_mode
    res &= await self._device.set_path(self._device.getId(), self.embedded_id, "fanControl", f"/operationModes/{operationmode}/fanDirection/vertical/currentMode", new_vMode)
    ^^^
UnboundLocalError: cannot access local variable 'res' where it is not associated with a value

**Comment by jwillemsen** [comment]
@DJMAXIZA The res error should be fixed in https://github.com/jwillemsen/daikin_residential_altherma/releases/tag/v3.2.9, thanks for reporting. Please attach your device diagnostics, there we can see what your device provides for data, do you see energy usage in the onecta app?

For the delay there is already https://github.com/jwillemsen/daikin_residential_altherma/issues/10, going to have a look at that as soon as possible.

**Comment by jwillemsen** [comment]
Thanks for the device diagnostics, looks this device has no energy and no demandControl settings. The stepValue is coming from the daikin settings, there it has a stepValue of 0.5, that is way we use

**Comment by PskNorz** [comment]
> @PskNorz Make sure you use https://github.com/jwillemsen/daikin_residential_altherma, I have added a PR to get it listed on HACS, but on HACS it is still not there, so don't use HACS right now for this integration

Got it thanks!
