### ISSUE TITLE
No climate entity’s for FVXM25A units

### ISSUE THREAD

**Issue by gzeel** [rospogrigio/daikin_residential#2]
I’ve succesfully added the integration to my Home Assistant setup. The integration is properly showing my 3 airco devices. However, for my two FVXM25A units, the climate entity doesn’t exists. All other sensors for these units (and streaming switch) are present.

The climate entity does exists for my FTXM35R unit.
![6D3C2D8B-4360-47C7-BF56-953B2DDF6F54](https://user-images.githubusercontent.com/35912246/125940618-f3d5e229-0c07-4239-9c08-c88cf5c1607b.jpeg)
![ECE09135-9230-48B2-BFA9-E0045C465D04](https://user-images.githubusercontent.com/35912246/125940621-640dc633-f9a4-431f-9614-c7665268a650.jpeg)

I don’t know if it has anything to do with this, but I have this error message in the HA log
`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/daikin_residential/climate.py", line 84, in async_setup_entry
    async_add_entities([DaikinClimate(device)], update_before_add=True)
  File "/config/custom_components/daikin_residential/climate.py", line 98, in __init__
    ATTR_SWING_MODE: self._device.swing_modes,
  File "/config/custom_components/daikin_residential/daikin_base.py", line 233, in swing_modes
    hMode = self.getData(ATTR_HSWING_MODE)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 107, in getData
    return self.get_data(cmd_set[0], cmd_set[1], cmd_set[2])
  File "/config/custom_components/daikin_residential/device.py", line 168, in get_data
    return self.managementPoints[managementPoint][dataPoint][dataPointPath]
KeyError: '/operationModes/dry/fanDirection/horizontal/currentMode' `

**Comment by rospogrigio** [comment]
Oh, I see, probably your devices don't provide horizontal swing and I have a missing check. Can you please try PR #3 and see if it solves your problem?

**Comment by gzeel** [comment]
> Oh, I see, probably your devices don't provide horizontal swing and I have a missing check. Can you please try PR #3 and see if it solves your problem?

Thanks! It works as in that I see the entity now, but it is in an unavailable state.
With the following log:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 383, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 588, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 666, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 455, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 298, in state_attributes
    data[ATTR_SWING_MODE] = self.swing_mode
  File "/config/custom_components/daikin_residential/climate.py", line 216, in swing_mode
    return self._device.swing_mode
  File "/config/custom_components/daikin_residential/daikin_base.py", line 218, in swing_mode
    hMode = self.getValue(ATTR_HSWING_MODE)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 111, in getValue
    return self.getData(param)["value"]
TypeError: 'NoneType' object is not subscriptable `

**Comment by smoldersonline** [comment]
Thanks a lot for this integration - greatly appreciated!

Same issue as described above with my FVXM50A unit.

I'm a bit of a Git n00b. How do I 'try PR #3'?

**Comment by smoldersonline** [comment]
Nevermind my last question on 'try PR #3'. I got it.

**Comment by rospogrigio** [comment]
Good job @smoldersonline , I like seeing people learn autonomously 😉 
To both of you: I should have fixed it now, can you try again PR #3 ?
Bye!

**Comment by gzeel** [comment]
> Good job @smoldersonline , I like seeing people learn autonomously 😉
> To both of you: I should have fixed it now, can you try again PR #3 ?
> Bye!

Yippie ka yee, it works. Thanks!

**Comment by rospogrigio** [comment]
Ok, I'll publish a new release then, thank you!

**Comment by smoldersonline** [comment]
Works like charm! Thank you much.
