### ISSUE TITLE
[Issue]: Fail to start with HA 2024.2.0

### ISSUE THREAD

**Issue by bogdanioanliviu** [rospogrigio/daikin_residential#204]
With the version of HA 2024.2.0 core this integration fails with the following error: 

```
2024-02-08 06:59:58.063 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'daikin_residential': Unable to import component: No module named 'oic'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/daikin_residential/__init__.py", line 13, in <module>
    from .daikin_api import DaikinApi
  File "/config/custom_components/daikin_residential/daikin_api.py", line 11, in <module>
    from oic.oic import Client
ModuleNotFoundError: No module named 'oic'
```

I think this is do to HA now using python 3.12. 
No diagnostics logs as the add-on it's not starting.

**Comment by jeroen911** [comment]
I have the same problem, running home assintant in Docker.

`2024-02-08 13:55:53.489 ERROR (MainThread) [custom_components.daikin_residential.config_flow] Failed to initialize DaikinApi: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).

2024-02-08 13:55:56.594 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Daikin for daikin_residential
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 442, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/daikin_residential/__init__.py", line 84, in async_setup_entry
daikin_api = DaikinApi(hass, entry)
^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/daikin_residential/daikin_api.py", line 54, in __init__
self.openIdClient = Client(client_id=self.openIdClientId, config=configuration)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/oic/oic/__init__.py", line 354, in __init__
self.settings = settings or OicClientSettings()
^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/oic/utils/settings.py", line 96, in __init__
super().__init__(
File "/usr/local/lib/python3.12/site-packages/oic/utils/settings.py", line 51, in __init__
self.client_cert = client_cert
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/oic/utils/settings.py", line 73, in __setattr__
raise SettingsException(
oic.utils.settings.SettingsException: client_cert has a type of <class 'NoneType'>, expected any of (<class 'str'>, <class 'tuple'>).`

**Comment by bogdanioanliviu** [comment]
A new version of HA 2024.2.1 was release. This version fix the error for this integration. 
I think this can be closed. 
Thank you
