### ISSUE TITLE
[Issue]: Error loading integration

### ISSUE THREAD

**Issue by martijnrusschen** [rospogrigio/daikin_residential#211]
After rebooting HA, I'm seeing an error loading the integration. See error log below:
```
Error setting up entry Daikin for daikin_residential
Traceback (most recent call last):
  File "/config/custom_components/daikin_residential/daikin_api.py", line 393, in retrieveAccessToken
    raise Exception("Unknown Login error: " + response["errorDetails"])
Exception: Unknown Login error: Missing required fields for registration: data.profile.communicationLanguage, data.profile.countryResidence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/daikin_residential/daikin_api.py", line 177, in refreshAccessToken
    await self.retrieveAccessToken(data[CONF_EMAIL], data[CONF_PASSWORD])
  File "/config/custom_components/daikin_residential/daikin_api.py", line 395, in retrieveAccessToken
    raise Exception("Login failed: %s", e)
Exception: ('Login failed: %s', Exception('Unknown Login error: Missing required fields for registration: data.profile.communicationLanguage, data.profile.countryResidence'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/__init__.py", line 85, in async_setup_entry
    devices = await daikin_api.getCloudDevices()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/daikin_api.py", line 488, in getCloudDevices
    self.json_data = await self.getCloudDeviceDetails()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/daikin_api.py", line 484, in getCloudDeviceDetails
    return await self.doBearerRequest("/v1/gateway-devices")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/daikin_residential/daikin_api.py", line 116, in doBearerRequest
    await self.refreshAccessToken()
  File "/config/custom_components/daikin_residential/daikin_api.py", line 183, in refreshAccessToken
    raise Exception(
Exception: Token refresh was not successful! Status: 400
```

**Comment by martijnrusschen** [comment]
Could this be because of the upcoming deprecation? I'll try using the other integration to see if that works.

**Comment by jwillemsen** [comment]
Same as #209

**Comment by martijnrusschen** [comment]
Thanks, migrated and fixed the issue.
