### ISSUE TITLE
Device is missing entity

### ISSUE THREAD

**Issue by 1981nick1982** [rospogrigio/daikin_residential#34]
I have read 4 devices and on 3 it loads all 10 entities correctly and works perfectly from google home. However, the 4th device is missing the Climate.xxxx entity, which makes it invisible. As a result, it also does not show this device correctly in Hassio.

**Comment by 1981nick1982** [comment]
Maybe it has something to do with this?



Logger: homeassistant.helpers.entity
Source: custom_components/daikin_residential/daikin_api.py:508
Integration: Daikin Residential Controller (documentation, issues)
First occurred: 2 december 2021 23:28:52 (1133 occurrences)
Last logged: 09:01:09

    Update for sensor.slaapkamer_vic_inside_temperature fails
    Update for climate.slaapkamer fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
    raise exc
  File "/config/custom_components/daikin_residential/sensor.py", line 122, in async_update
    await self._device.api.async_update()
  File "/config/custom_components/daikin_residential/daikin_api.py", line 508, in async_update
    if dev_data["managementPoints"][1]["econoMode"]["value"] == "on":
KeyError: 'econoMode'

**Comment by 1981nick1982** [comment]
Fixed with the fix economade version.
