### ISSUE TITLE
BRP069C4x does not work anymore

### ISSUE THREAD

**Issue by rploeg** [rospogrigio/daikin_residential#38]
Hi,

I have two BRP069C4x devices of Daikin and one BRP069B4x. The last one is working fine.

Since a couple of days one of the BRP069C4x  didn't worked anymore, today I did a reboot and now the second BRP069C4x doesn't work anymore. The BRP069B4x is still working correctly.

I see the following error in my homeassistant logs:

`2021-12-06 22:22:52 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up daikin_residential platform for sensor 
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state
if (state := self.state) is None:
File "/config/custom_components/daikin_residential/sensor.py", line 137, in state
return self._device.inside_temperature
File "/config/custom_components/daikin_residential/daikin_base.py", line 286, in inside_temperature
return float(self.getValue(ATTR_INSIDE_TEMPERATURE))
TypeError: float() argument must be a string or a number, not 'NoneType'`

or

`2021-12-06 22:32:52 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.laurens_streamer fails
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 468, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 658, in async_device_update
raise exc
File "/config/custom_components/daikin_residential/switch.py", line 75, in async_update
await self._device.api.async_update()
File "/config/custom_components/daikin_residential/daikin_api.py", line 534, in async_update
if dev_data["managementPoints"][1]["streamerMode"]["value"] == "on"
KeyError: 'streamerMode'`

What could be wrong?

I am running:
Version | core-2021.11.5
Installation Type | Home Assistant OS

`

**Comment by rospogrigio** [comment]
Can you post your json? You can get it using the dump_json.py script you find in the tools folder.

**Comment by rploeg** [comment]
Thanks, but how do I run the py file on my raspberry Home Assistant OS?

**Comment by rploeg** [comment]
So installed the SSH add-on, but python scripts cannot be executed under hassio OS. Removed the add-on and reinstalled it again. One is working again (like before) and the other two still given the same errors:

![image](https://user-images.githubusercontent.com/49752333/144932707-144232d9-bfb4-4c1f-ae86-1477cb8fc282.png)

Working controls and sensors with the BRP069C4x :

![image](https://user-images.githubusercontent.com/49752333/144932758-1e542688-36c6-4945-892d-5d9c621abc66.png)

not working controls, but sensors are working like temperature etc) for the other two: units of BRP069B4x:

![image](https://user-images.githubusercontent.com/49752333/144932842-7a94f92d-a0f4-41fd-977b-c38bc6cc435a.png)

**Comment by rospogrigio** [comment]
Can't do much without having a look at the JSON, sorry.
Did you upgrade the firmware, by any chance?

**Comment by rploeg** [comment]
Have added the lines to the script, but the JSON file is empty:

![image](https://user-images.githubusercontent.com/49752333/144934037-a291bbf7-6faa-40c7-a0ee-ba36d25197b0.png)

I have added the lines here:

![image](https://user-images.githubusercontent.com/49752333/144934136-f2dfa154-e35f-4a3f-a397-86d812f255af.png)

is that correct?

**Comment by rospogrigio** [comment]
You made a partial modification, you should replace devices with json_data in line 490...

**Comment by rploeg** [comment]
Sorry for all the question and thanks for the great support; have changed it:

![image](https://user-images.githubusercontent.com/49752333/144935635-c274a0a1-eb69-42a2-abe9-a3ee87c43d4a.png)

But see now this error in the log:

`2021-12-06 23:46:16 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Daikin for daikin_residential
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/daikin_residential/__init__.py", line 85, in async_setup_entry
devices = await daikin_api.getCloudDevices()
File "/config/custom_components/daikin_residential/daikin_api.py", line 490, in getCloudDevices
json.dump(json_data, jsonFile, indent=4, sort_keys=True)
NameError: name 'json' is not defined`

So JSON file is still empty (off course)

**Comment by rospogrigio** [comment]
You are missing an `import json` line at the top...

**Comment by rploeg** [comment]
Thank you, that did the trick. here is the file:

[daikin_data.zip](https://github.com/rospogrigio/daikin_residential/files/7664074/daikin_data.zip)

**Comment by rospogrigio** [comment]
OK don't have time to look at this now, I'll let you know when I understand what's wrong 😉

**Comment by rospogrigio** [comment]
OK I saw what's wrong. Your BRP069B4x device does not have the streamer option, so it's crashing due to a debug line.
Then, one of your BRP069C4x devices does not provide the roomTemperature sensor which is veeeeery weird (it provides a roomHumidity sensor, instead)...
I should have fixed them in PR #39: can you try it and let me know if it works for you? You should download all the changed files from there and replace those you find in your integration.
Let me know...

**Comment by rploeg** [comment]
Great, yes it is working again!

**Comment by rospogrigio** [comment]
Ok I'm publishing a new release then.
Thank you for reporting the issue 😉

**Comment by rploeg** [comment]
Hi,

I have updated to the latest version (where this fix was included), but when I now set the command heat on one the airco's, I get this error:

Logger: homeassistant
Source: custom_components/daikin_residential/daikin_base.py:291
Integration: Daikin Residential Controller (documentation, issues)
First occurred: 7:49:49 PM (408 occurrences)
Last logged: 10:05:20 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 728, in _update_entity_states
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 473, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 519, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 492, in _stringify_state
    if (state := self.state) is None:
  File "/config/custom_components/daikin_residential/sensor.py", line 137, in state
    return self._device.inside_temperature
  File "/config/custom_components/daikin_residential/daikin_base.py", line 291, in inside_temperature
    return float(self.getValue(ATTR_INSIDE_TEMPERATURE))
TypeError: float() argument must be a string or a number, not 'NoneType'

I get it on both airco's of the C4X type.

**Comment by rospogrigio** [comment]
OK I fixed this in this PR: #40 , can you try?
In any case: some of your aircos do not provide the **_roomTemperature_** sensor and it is very very strange, I think you really should investigate this. Does the Daikin app show the current room temperature value? I'm pretty sure it does, so I don't understand why you don't find this data in your json.

**Comment by rploeg** [comment]
Thanks. Yes sometimes of one the airco's I don't see the intern temperature and sometimes it does
