### ISSUE TITLE
Daikin units visible, but not all settings available

### ISSUE THREAD

**Issue by jwillemsen** [rospogrigio/daikin_residential#51]
I get the daikin units visible within HA with this component, but not all entities are shown and I can't enable/disable the unit. attached the json file (removed the internal ids). Any idea what could be the problem, are new FTXM units with built in wifi
 
[daikin_data.json.txt](https://github.com/rospogrigio/daikin_residential/files/7925247/daikin_data.json.txt)

**Comment by jwillemsen** [comment]
From the log with warnings enabled I see

```
2022-01-24 12:55:13 ERROR (MainThread) [homeassistant.components.climate] Error while setting up daikin_residential platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/daikin_residential/climate.py", line 85, in async_setup_entry
    async_add_entities([DaikinClimate(device)], update_before_add=True)
  File "/config/custom_components/daikin_residential/climate.py", line 99, in __init__
    ATTR_SWING_MODE: self._device.swing_modes,
  File "/config/custom_components/daikin_residential/daikin_base.py", line 239, in swing_modes
    hMode = self.getData(ATTR_HSWING_MODE)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 106, in getData
    cmd_set = self.getCommandSet(param)
  File "/config/custom_components/daikin_residential/daikin_base.py", line 101, in getCommandSet
    cmd_set[2] = cmd_set[2].replace("%operationMode%", operation_mode)
TypeError: replace() argument 2 must be str, not None
```
