### ISSUE TITLE
Not working for device BRP069A78 (Altherma 3 heat pump)

### ISSUE THREAD

**Issue by speleolontra** [rospogrigio/daikin_residential#8]
Hi, ihave tried this component for my daikin heat pump. 
I see in devices: "BRP069A78" but there's only one entity "unavailable".
![Immagine 2021-08-10 233140](https://user-images.githubusercontent.com/10747617/128937831-2cace87d-3473-4af0-80a7-963c00a1db8e.JPG)

In logs i have:
2021-08-10 23:20:03 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Daikin for daikin_residential
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 249, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/daikin_residential/__init__.py", line 56, in async_setup_entry
await daikin_api.getCloudDeviceDetails()
File "/config/custom_components/daikin_residential/daikin_api.py", line 150, in getCloudDeviceDetails
json.dump(devices, jsonFile, indent=4, sort_keys=True)
NameError: name 'devices' is not defined

Maybe my device is not supported.
Thanks for your great work!
Lontra

**Comment by speleolontra** [comment]
Hi, 
that's i'm obtained copy tools folder and then copy "tokenset.json" in the same directory.
Can you confirm that the right folder for "tokenset.json" is in the same directory of configuration.yaml?

```

[
    {
        "_id": "70d77c24-81d1-4575-9a80-xxxxxxxxxxxxxxx",
        "deviceModel": "Altherma",
        "embeddedId": "e3082b6e-c3e6-44e2-8899-xxxxxxxxxxxxx",
        "id": "70d77c24-81d1-4575-9a80-xxxxxxxxxxxx",
        "isCloudConnectionUp": {
            "settable": false,
            "value": true
        },
        "lastUpdateReceived": "2021-08-11T20:08:04.365Z",
        "managementPoints": [
            {
                "embeddedId": "gateway",
                "firmwareVersion": {
                    "maxLength": 8,
                    "settable": false,
                    "value": "3.0.2"
                },
                "iconId": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": 3
                },
                "ipAddress": {
                    "maxLength": 15,
                    "settable": false,
                    "value": "192.168.8.xxxxxxxxxx"
                },
                "macAddress": {
                    "maxLength": 17,
                    "settable": false,
                    "value": "ec:2e:98:xxxxxxxxxxxxx"
                },
                "managementPointCategory": "secondary",
                "managementPointType": "gateway",
                "modelInfo": {
                    "maxLength": 9,
                    "settable": false,
                    "value": "BRP069A78"
                },
                "name": {
                    "maxLength": 63,
                    "requiresReboot": false,
                    "settable": true,
                    "value": "Gateway"
                },
                "serialNumber": {
                    "maxLength": 16,
                    "settable": false,
                    "value": "0034131"
                }
            },
            {
                "consumptionData": {
                    "ref": "#consumptionData",
                    "requiresReboot": false,
                    "settable": false,
                    "value": {
                        "electrical": {
                            "cooling": {
                                "d": [
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    null
                                ],
                                "m": [
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    0,
                                    0,
                                    null,
                                    null,
                                    null,
                                    null
                                ],
                                "w": [
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    null,
                                    null,
                                    null,
                                    null
                                ]
                            },
                            "heating": {
                                "d": [
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    null
                                ],
                                "m": [
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    0,
                                    0,
                                    null,
                                    null,
                                    null,
                                    null
                                ],
                                "w": [
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    null,
                                    null,
                                    null,
                                    null
                                ]
                            }
                        }
                    }
                },
                "controlMode": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": "leavingWaterTemperature",
                    "values": [
                        "leavingWaterTemperature",
                        "externalRoomTemperature",
                        "roomTemperature"
                    ]
                },
                "embeddedId": "climateControlMainZone",
                "errorCode": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": ""
                },
                "holidayMode": {
                    "ref": "#holidayMode",
                    "requiresReboot": false,
                    "settable": true,
                    "value": {
                        "enabled": false,
                        "endDate": "2017-01-01",
                        "startDate": "2017-01-01"
                    }
                },
                "iconId": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": 8
                },
                "isHolidayModeActive": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInEmergencyState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInErrorState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInInstallerState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInWarningState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "managementPointCategory": "primary",
                "managementPointSubType": "mainZone",
                "managementPointType": "climateControl",
                "name": {
                    "maxLength": 63,
                    "requiresReboot": false,
                    "settable": true,
                    "value": "Pavimento radiante"
                },
                "onOffMode": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": "off",
                    "values": [
                        "off",
                        "on"
                    ]
                },
                "operationMode": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": "heating",
                    "values": [
                        "heating",
                        "cooling",
                        "auto"
                    ]
                },
                "sensoryData": {
                    "ref": "#sensoryData",
                    "settable": false,
                    "value": {
                        "leavingWaterTemperature": {
                            "maxValue": 127,
                            "minValue": -127,
                            "requiresReboot": false,
                            "settable": false,
                            "stepValue": 1,
                            "value": 28
                        },
                        "outdoorTemperature": {
                            "maxValue": 127,
                            "minValue": -127,
                            "requiresReboot": false,
                            "settable": false,
                            "stepValue": 1,
                            "value": 26
                        }
                    }
                },
                "setpointMode": {
                    "requiresReboot": true,
                    "settable": false,
                    "value": "weatherDependent",
                    "values": [
                        "fixed",
                        "weatherDependentHeatingFixedCooling",
                        "weatherDependent"
                    ]
                },
                "temperatureControl": {
                    "ref": "#temperatureControl",
                    "settable": true,
                    "value": {
                        "operationModes": {
                            "auto": {
                                "setpoints": {
                                    "leavingWaterOffset": {
                                        "maxValue": 10,
                                        "minValue": -10,
                                        "requiresReboot": false,
                                        "settable": true,
                                        "stepValue": 1,
                                        "value": 0
                                    }
                                }
                            },
                            "cooling": {
                                "setpoints": {
                                    "leavingWaterOffset": {
                                        "maxValue": 10,
                                        "minValue": -10,
                                        "requiresReboot": false,
                                        "settable": true,
                                        "stepValue": 1,
                                        "value": 0
                                    }
                                }
                            },
                            "heating": {
                                "setpoints": {
                                    "leavingWaterOffset": {
                                        "maxValue": 10,
                                        "minValue": -10,
                                        "requiresReboot": false,
                                        "settable": true,
                                        "stepValue": 1,
                                        "value": 0
                                    }
                                }
                            }
                        }
                    }
                }
            },
            {
                "consumptionData": {
                    "ref": "#consumptionData",
                    "requiresReboot": false,
                    "settable": false,
                    "value": {
                        "electrical": {
                            "heating": {
                                "d": [
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    0,
                                    1,
                                    null
                                ],
                                "m": [
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    null,
                                    64,
                                    5,
                                    null,
                                    null,
                                    null,
                                    null
                                ],
                                "w": [
                                    1,
                                    0,
                                    1,
                                    0,
                                    1,
                                    0,
                                    1,
                                    0,
                                    0,
                                    1,
                                    null,
                                    null,
                                    null,
                                    null
                                ]
                            }
                        }
                    }
                },
                "embeddedId": "domesticHotWaterTank",
                "errorCode": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": ""
                },
                "heatupMode": {
                    "requiresReboot": true,
                    "settable": false,
                    "value": "reheatOnly",
                    "values": [
                        "reheatOnly",
                        "reheatSchedule",
                        "scheduleOnly"
                    ]
                },
                "iconId": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": 6
                },
                "isHolidayModeActive": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInEmergencyState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInErrorState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInInstallerState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isInWarningState": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "isPowerfulModeActive": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": false
                },
                "managementPointCategory": "primary",
                "managementPointType": "domesticHotWaterTank",
                "name": {
                    "maxLength": 63,
                    "requiresReboot": false,
                    "settable": true,
                    "value": "Acqua calda sanitaria"
                },
                "onOffMode": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": "off",
                    "values": [
                        "off",
                        "on"
                    ]
                },
                "operationMode": {
                    "settable": false,
                    "value": "heating",
                    "values": [
                        "heating"
                    ]
                },
                "powerfulMode": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": "off",
                    "values": [
                        "off",
                        "on"
                    ]
                },
                "sensoryData": {
                    "ref": "#sensoryData",
                    "settable": true,
                    "value": {
                        "tankTemperature": {
                            "maxValue": 127,
                            "minValue": -127,
                            "requiresReboot": false,
                            "settable": false,
                            "stepValue": 1,
                            "value": 39
                        }
                    }
                },
                "setpointMode": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": "fixed",
                    "values": [
                        "fixed",
                        "weatherDependent"
                    ]
                },
                "temperatureControl": {
                    "ref": "#temperatureControl",
                    "settable": true,
                    "value": {
                        "operationModes": {
                            "heating": {
                                "setpoints": {
                                    "domesticHotWaterTemperature": {
                                        "maxValue": 60,
                                        "minValue": 30,
                                        "requiresReboot": false,
                                        "settable": false,
                                        "stepValue": 1,
                                        "value": 43
                                    }
                                }
                            }
                        }
                    }
                }
            },
            {
                "eepromVersion": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "3608726-34"
                },
                "embeddedId": "indoorUnitHydro",
                "iconId": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": 4
                },
                "managementPointCategory": "secondary",
                "managementPointType": "indoorUnitHydro",
                "modelInfo": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "EHVX04S23EA6V"
                },
                "name": {
                    "maxLength": 63,
                    "requiresReboot": false,
                    "settable": true,
                    "value": "Indoor Hydro Unit"
                },
                "softwareVersion": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "0221"
                }
            },
            {
                "embeddedId": "outdoorUnit",
                "iconId": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": 5
                },
                "managementPointCategory": "secondary",
                "managementPointType": "outdoorUnit",
                "modelInfo": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": ""
                },
                "name": {
                    "maxLength": 63,
                    "requiresReboot": false,
                    "settable": true,
                    "value": "Outdoor Unit"
                },
                "softwareVersion": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "FFFF"
                }
            },
            {
                "dateTime": {
                    "requiresReboot": false,
                    "settable": false,
                    "value": "2021-08-11T16:02:09"
                },
                "embeddedId": "userInterface",
                "firmwareVersion": {
                    "deprecated": "DEPRECATED",
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "6.5.0"
                },
                "iconId": {
                    "requiresReboot": false,
                    "settable": true,
                    "value": 6
                },
                "managementPointCategory": "secondary",
                "managementPointType": "userInterface",
                "miconId": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "21008A01"
                },
                "modelInfo": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "EHVX04S23EA6V"
                },
                "name": {
                    "maxLength": 63,
                    "requiresReboot": false,
                    "settable": true,
                    "value": "User Interface"
                },
                "softwareVersion": {
                    "maxLength": 16,
                    "requiresReboot": false,
                    "settable": false,
                    "value": "6.5.0"
                }
            }
        ],
        "timestamp": "2021-08-11T20:08:04.365Z",
        "type": "heating-wlan"
    }
]
```

**Comment by rospogrigio** [comment]
Yes, that's ok. I need some time to check what's going on and I'm going on holiday so don't expect a reply before 10 days or so.
Bye...

**Comment by rospogrigio** [comment]
Sorry @speleolontra but what is this device?? It's a heat pump?? This integration is meant for air conditioners... this device has totally different json data structure, I believe there's nothing I can do with it. Someone should take my work and adapt it to your device...

**Comment by rospogrigio** [comment]
Yes, I'm italian, you can write me at rospogrigio@gmail.com 😉
